/**
 * Canonical CSV → HubSpot property mapping. Single source of truth.
 *
 * Generated by inspection of the live HubSpot schema (see schemas/*.json).
 * If HubSpot schema changes, re-pull and update this file.
 *
 * Structure for each entry:
 *   csv:      CSV header name as it appears in the file
 *   prop:     HubSpot property name (snake_case, matches schema exactly)
 *   type:     HubSpot property type — drives coercion at send time
 *             'string' | 'number' | 'bool' | 'date' | 'enumeration'
 *
 * Fields with no HubSpot target are intentionally omitted (dropped at parse).
 */

// CIF CSV → Contact or Company, depending on classification.
// Only truly-common fields go here. Verified against HubSpot schemas/contacts.json
// and schemas/companies.json.
const CIF_COMMON = [
  { csv: 'CIFNum',              prop: 'cif_number',                              type: 'string' },
  { csv: 'Email',               prop: 'email',                                   type: 'string' },
  { csv: 'PhoneNumber',         prop: 'phone',                                   type: 'string' },
  { csv: 'Address1',            prop: 'address',                                 type: 'string' },
  { csv: 'City',                prop: 'city',                                    type: 'string' },
  { csv: 'State',               prop: 'state',                                   type: 'string' },
  { csv: 'ZipCode',             prop: 'zip',                                     type: 'string' },
  { csv: 'HashSSN',             prop: 'hashed_ssn',                              type: 'string' },
  { csv: 'DoNotCall',           prop: 'dnc_flag_yn',                             type: 'bool' },
  { csv: 'InsiderCode',         prop: 'insider_code',                            type: 'string' },
  { csv: 'InsufficientAddress', prop: 'insufficient_address_yn',                 type: 'bool' },
  { csv: 'CLFFlag',             prop: 'clf_flag_yn',                             type: 'bool' },
  { csv: 'CivAtWork',           prop: 'civistawork_yn',                          type: 'bool' },
  { csv: 'OrigCustDate',        prop: 'orginal_customer_date',                   type: 'date' },   // HubSpot typo preserved
  { csv: 'Deceased',            prop: 'deceased_flag_yn',                        type: 'bool' },
  { csv: 'ClassCode',           prop: 'class_code',                              type: 'string' },
  { csv: 'TaxIdType',           prop: 'tax_id_type',                             type: 'enumeration' },
  { csv: 'CustRelNum',          prop: 'customer_relationship_number',            type: 'string' },
  { csv: 'DigBank',             prop: 'digital_banking_flag_yn',                 type: 'bool' },
  { csv: 'ATMDebitCard',        prop: 'atmdebit_card_yn',                        type: 'bool' },
  { csv: 'Q2userID',            prop: 'q2_user_id',                              type: 'string' },
  { csv: 'LastLogin',           prop: 'last_login',                              type: 'date' },
  { csv: 'RecurTrans',          prop: 'recurring_transactions_yn',               type: 'bool' },
  { csv: 'StmtType',            prop: 'stmt_type',                               type: 'enumeration' },
  { csv: 'EnrollmentDt',        prop: 'enrollment_date',                         type: 'date' },
  { csv: 'CentralGroupID',      prop: 'central_group_id',                        type: 'string' },
  { csv: 'TextOptIn',           prop: 'text_opt_in',                             type: 'bool' },
  { csv: 'DiscAcpt',            prop: 'estatement_disclosure_acceptance_date',   type: 'date' },
];

// Contact-only properties (don't exist on HubSpot companies).
const CIF_CONTACT_ONLY = [
  { csv: 'FirstName',   prop: 'firstname',                  type: 'string' },
  { csv: 'LastName',    prop: 'lastname',                   type: 'string' },
  { csv: 'Birthday',    prop: 'date_of_birth',              type: 'date' },
  { csv: 'Address2',    prop: 'street_address_2',           type: 'string' },
  { csv: 'PrivBanking', prop: 'private_banking_flag_yn',    type: 'bool' },
  { csv: 'Minor',       prop: 'minor_flag_yn',              type: 'bool' },
];

// Company-only properties (don't exist on HubSpot contacts).
const CIF_COMPANY_ONLY = [
  { csv: 'FullName',  prop: 'name',                          type: 'string' },
  { csv: 'NAICSCode', prop: 'naics_code',                    type: 'string' },
  { csv: 'TM',        prop: 'treasury_management_flag_yn',   type: 'bool' },
];

const CIF_CONTACT_FIELDS = [...CIF_COMMON, ...CIF_CONTACT_ONLY];
const CIF_COMPANY_FIELDS = [...CIF_COMMON, ...CIF_COMPANY_ONLY];

// DDA CSV → Deposits (custom object 2-60442978).
const DDA_FIELDS = [
  { csv: 'PrimaryKey',    prop: 'primary_key',              type: 'string' },
  { csv: 'Acctlast4',     prop: 'last_4_account_digits',    type: 'string' },
  { csv: 'CIF#',          prop: 'cif_number',               type: 'string' },
  { csv: 'InterestRate',  prop: 'interest_rate',            type: 'number' },
  { csv: 'accttype',      prop: 'account_type',             type: 'enumeration' },
  { csv: 'acctdesc',      prop: 'account_description',      type: 'string' },
  { csv: 'opendate',      prop: 'date_opened',              type: 'date' },
  { csv: 'closedate',     prop: 'date_closed',              type: 'date' },
  { csv: 'slsassoc',      prop: 'sales_associate',          type: 'string' },
  { csv: 'dtlastactive',  prop: 'date_last_active',         type: 'date' },
  { csv: 'currentbal',    prop: 'current_balance',          type: 'number' },
  { csv: 'yestbal',       prop: 'yesterdays_balance',       type: 'number' },
  { csv: 'branchnum',     prop: 'branch_number',            type: 'string' },
  { csv: 'officrcode',    prop: 'officer_name',             type: 'string' },
  { csv: 'acctstatus',    prop: 'deposit_account_status',   type: 'enumeration' },
  { csv: 'promocode',     prop: 'promo_code',               type: 'string' },
  { csv: 'openonline',    prop: 'opened_online_yn',         type: 'bool' },
  // 'relationship' field in CSV has no HubSpot equivalent — intentionally dropped.
];

// Loans CSV → Loans (custom object 2-60442977).
const LOANS_FIELDS = [
  { csv: 'PrimaryKey',      prop: 'primary_key',            type: 'string' },
  { csv: 'acctlast4',       prop: 'last_4_account_digits',  type: 'string' },
  { csv: 'CIFNum',          prop: 'cif_number',             type: 'string' },
  { csv: 'InterestRate',    prop: 'interest_rate',          type: 'number' },
  { csv: 'accttype',        prop: 'account_type',           type: 'enumeration' },
  { csv: 'loantype',        prop: 'loan_type',              type: 'enumeration' },
  { csv: 'origdate',        prop: 'orgination_date',        type: 'date' },   // HubSpot typo, preserved
  { csv: 'maturitydate',    prop: 'maturity_date',          type: 'date' },
  { csv: 'slsassoc',        prop: 'sales_associate',        type: 'string' },
  { csv: 'lastactivedate',  prop: 'date_last_active',       type: 'date' },
  { csv: 'currbal',         prop: 'current_balance',        type: 'number' },
  { csv: 'branchnum',       prop: 'branch_number',          type: 'string' },
  { csv: 'officrcode',      prop: 'officer_name',           type: 'string' },
  { csv: 'acctstatus',      prop: 'loan_status',            type: 'enumeration' },
  { csv: 'origbal',         prop: 'original_balance',       type: 'number' },
  // 'relationship' dropped — no HubSpot target.
];

// CD CSV → Time Deposits (custom object 2-60442980).
const CD_FIELDS = [
  { csv: 'PrimaryKey',    prop: 'primary_key',              type: 'string' },
  { csv: 'AcctLast4',     prop: 'last_4_account_digits',    type: 'string' },
  { csv: 'CIFNum',        prop: 'cif_number',               type: 'string' },
  { csv: 'InterestRate',  prop: 'interest_rate',            type: 'number' },
  { csv: 'accttype',      prop: 'account_type',             type: 'enumeration' },
  { csv: 'acctdesc',      prop: 'account_description',      type: 'string' },
  { csv: 'issuedate',     prop: 'issue_date',               type: 'date' },
  { csv: 'maturitydate',  prop: 'maturity_date',            type: 'date' },
  { csv: 'slsassoc',      prop: 'sales_associate',          type: 'string' },
  { csv: 'currbal',       prop: 'current_balance',          type: 'number' },
  { csv: 'branchnum',     prop: 'branch_number',            type: 'string' },
  { csv: 'officrcode',    prop: 'officer_name',             type: 'string' },
  { csv: 'acctstatus',    prop: 'time_deposit_status',      type: 'enumeration' },
  { csv: 'openonline',    prop: 'opened_online_yn',         type: 'bool' },
  // 'relationship' dropped.
];

// Debit Card CSV → Debit Cards (custom object 2-60442979).
const DEBIT_CARDS_FIELDS = [
  { csv: 'CIF#',             prop: 'cif_number',                       type: 'string' },
  { csv: 'Acctlast4',        prop: 'last_4_of_associated_account',     type: 'string' },
  { csv: 'AcctType',         prop: 'associated_account_type',          type: 'enumeration' },
  { csv: 'Last4DebitCard',   prop: 'last_4_of_debit_card_digits',      type: 'string' },
  { csv: 'CardStatus',       prop: 'card_status',                      type: 'enumeration' },
  { csv: 'Expiredate',       prop: 'expiration_date',                  type: 'date' },
  { csv: 'Lastuseddt',       prop: 'last_used',                        type: 'date' },
  { csv: 'POSLast30Days',    prop: 'pos_trans_count__last_30_day',     type: 'number' },
  { csv: 'ActivePOS',        prop: 'active_pos',                       type: 'bool' },
  // composite_key is generated (not in CSV) — handled specially in parser.
];

// Table name per source + destination HubSpot object ID.
const TABLES = {
  cif: {
    csvFile: 'HubSpot_CIF.csv',
    contactStaging: 'stg_contacts',
    companyStaging: 'stg_companies',
    contactObject: 'contacts',
    companyObject: 'companies',
    contactIdProperty: 'cif_number',
    companyIdProperty: 'cif_number',
    contactFields: CIF_CONTACT_FIELDS,
    companyFields: CIF_COMPANY_FIELDS,
  },
  dda: {
    csvFile: 'HubSpot_DDA.csv',
    staging: 'stg_deposits',
    object: '2-60442978',
    idProperty: 'primary_key',
    fields: DDA_FIELDS,
  },
  loans: {
    csvFile: 'HubSpot_Loan.csv',
    staging: 'stg_loans',
    object: '2-60442977',
    idProperty: 'primary_key',
    fields: LOANS_FIELDS,
  },
  cd: {
    csvFile: 'HubSpot_CD.csv',
    staging: 'stg_time_deposits',
    object: '2-60442980',
    idProperty: 'primary_key',
    fields: CD_FIELDS,
  },
  debit_cards: {
    csvFile: 'HubSpot_Debit_Card.csv',
    staging: 'stg_debit_cards',
    object: '2-60442979',
    idProperty: 'composite_key',
    fields: DEBIT_CARDS_FIELDS,
  },
};

/**
 * Classify a raw CIF CSV row as 'contact', 'company', or 'unclassified'.
 * Matches the business rules from CLAUDE.md:
 *   - TaxIdType='T' AND FirstName empty AND LastName empty → company
 *   - TaxIdType='T' AND FirstName+LastName populated      → contact (biz contact)
 *   - TaxIdType is non-null AND != 'T'                    → contact
 *   - anything else (NULL taxidtype, partial name data)   → unclassified
 * Operates on the RAW CSV row (keys are CSV header names like 'TaxIdType').
 */
function classifyCifRow(row) {
  const taxId = row.TaxIdType;
  const first = (row.FirstName || '').trim();
  const last  = (row.LastName  || '').trim();

  if (taxId === 'T') {
    if (first === '' && last === '') return 'company';
    if (first !== '' && last !== '') return 'contact';
    return 'unclassified';
  }
  if (taxId && taxId !== 'T') return 'contact';
  return 'unclassified';
}

module.exports = {
  TABLES,
  CIF_COMMON,
  CIF_CONTACT_ONLY,
  CIF_COMPANY_ONLY,
  CIF_CONTACT_FIELDS,
  CIF_COMPANY_FIELDS,
  DDA_FIELDS,
  LOANS_FIELDS,
  CD_FIELDS,
  DEBIT_CARDS_FIELDS,
  classifyCifRow,
};
